"""
File containing helper methods for contacting the postgres database.
"""
import os
import sys

import psycopg2


def connect():
    """
    Connect to the database and return the connection generated by psycopg2.
    
    @return: the connection
    """
    try:
        connection = psycopg2.connect(user=os.getenv('NCAABaseballUser'),
                                      password=os.getenv('NCAABaseballPassword'),
                                      host='localhost',
                                      port=5432,
                                      database='ncaa_baseball')
        return connection
    except psycopg2.Error as error:
        print("Error while connecting to ncaa_baseball, make sure your environment variables are "
              "set properly", error)
        sys.exit(1)


def get_year_info(year):
    """
    Get the ids for the year specified.
    
    @param year: the year to get the ids of
    @return: a dict containing the year_id, hitting_id, pitching_id, and fielding_id for that year
    """
    connection = connect()
    cursor = connection.cursor()
    cursor.execute('SELECT year_id, hitting_id, pitching_id, fielding_id '
                   'FROM year_info '
                   'WHERE year={year}'.format(year=year))
    ids = list(cursor.fetchone())
    connection.close()
    return {'year_id': ids[0], 'hitting_id': ids[1], 'pitching_id': ids[2], 'fielding_id': ids[3]}
