CREATE TABLE pitching_line
(
  game_id int NOT NULL REFERENCES game,
  roster_id int NOT NULL REFERENCES roster,
  app int CHECK (app = 0 OR app = 1),
  gs int CHECK (gs = 0 OR app = 1),
  ord int,
  w int CHECK (w = 0 OR w = 1),
  l int CHECK (l = 0 OR l = 1),
  sv int CHECK (sv = 0 OR sv = 1),
  ip float,
  p int,
  bf int,
  h int,
  dbl int,
  tpl int,
  hr int,
  bb int,
  ibb int,
  hbp int,
  r int,
  er int,
  ir int,
  irs int,
  fo int,
  go int,
  k int,
  kl int,
  sf int,
  sh int,
  bk int,
  wp int,
  cg int CHECK (cg = 0 OR cg = 1),
  sho int CHECK (sho = 0 OR sho = 1),
  UNIQUE (game_id, roster_id)
);
