CREATE TABLE pitching_line
(
  game_id int NOT NULL REFERENCES game,
  roster_id int NOT NULL REFERENCES roster,
  app int NOT NULL CHECK (app = 0 OR app = 1),
  gs int NOT NULL CHECK (gs = 0 OR app = 1),
  ord int NOT NULL,
  w int NOT NULL CHECK (w = 0 OR w = 1),
  l int NOT NULL CHECK (l = 0 OR l = 1),
  sv int NOT NULL CHECK (sv = 0 OR sv = 1),
  ip float NOT NULL,
  p int NOT NULL,
  bf int NOT NULL,
  h int NOT NULL,
  dbl int NOT NULL,
  tpl int NOT NULL,
  hr int NOT NULL,
  bb int NOT NULL,
  ibb int NOT NULL,
  hbp int NOT NULL,
  r int NOT NULL,
  er int NOT NULL,
  ir int NOT NULL,
  irs int NOT NULL,
  fo int NOT NULL,
  go int NOT NULL,
  k int NOT NULL,
  kl int NOT NULL,
  sf int NOT NULL,
  sh int NOT NULL,
  bk int NOT NULL,
  wp int NOT NULL,
  cg int NOT NULL CHECK (cg = 0 OR cg = 1),
  sho int NOT NULL CHECK (sho = 0 OR sho = 1),
  UNIQUE (game_id, roster_id)
);
